services:
  console.command_generator:
    class: WP\Console\Generator\CommandGenerator
    arguments: ['@console.extension_manager', '@console.translator_manager']
    tags:
      - { name: wordpress.generator }
  console.plugin_generator:
    class: WP\Console\Generator\PluginGenerator
    tags:
      - { name: wordpress.generator }
  console.meta_box_generator:
    class: WP\Console\Generator\MetaBoxGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.taxonomy_generator:
    class: WP\Console\Generator\TaxonomyGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.theme_generator:
    class: WP\Console\Generator\ThemeGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.shortcode_generator:
    class: WP\Console\Generator\ShortcodeGenerator
    tags:
      - { name: wordpress.generator }
  console.post_type_generator:
    class: WP\Console\Generator\PostTypeGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.menu_generator:
    class: WP\Console\Generator\MenuGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.toolbar_generator:
    class: WP\Console\Generator\ToolbarGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.sidebar_generator:
    class: WP\Console\Generator\SidebarGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.quicktag_generator:
    class: WP\Console\Generator\QuickTagGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.widget_generator:
    class: WP\Console\Generator\WidgetGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.user_contactmethods_generator:
    class: WP\Console\Generator\UserContactMethodsGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.register_base_generator:
    class: WP\Console\Generator\RegisterBaseGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }